# Generated by Django 5.0.6 on 2024-05-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='level',
            field=models.IntegerField(blank=True, choices=[('Завод', '0'), ('Розничная сеть', '1'), ('Индивидуальный предприниматель', '2')], null=True, verbose_name='Уровень звена'),
        ),
    ]
