# Generated by Django 5.0.6 on 2024-05-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_networknode_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='level',
            field=models.IntegerField(blank=True, choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], null=True, verbose_name='Уровень звена'),
        ),
    ]
